@baseUrl = http://localhost:8080/
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjM0ODkwNjQsImV4cCI6MTYyMzQ5NjI2NCwiYXVkIjoiNjBjMDc5OTk0NDI3MGY4YzNiYzg2M2RmIn0.Qn5k05jRBQZp5dLc7kLmXkwWgvnIUNMeGo1IPxVzcac

# @baseUrl = https://assignment-mangement.herokuapp.com/
# @accessToken = 

###
Post {{baseUrl}}auth/register
Content-Type: application/json

{
    "firstName": "rohit",
    "lastName": "bhagat",
    "email": "rohit1@yopmail.com",
    "password": "Hello@user"
}

###
Post {{baseUrl}}auth/verify-email
Content-Type: application/json

{
    "email": "cm9oaXQxMkB5b3BtYWlsLmNvbQ==",
    "otp": "NDAzMzcw"
}

###
Post {{baseUrl}}auth/login
Content-Type: application/json

{
    "email": "rohit12@yopmail.com",
    "password": "Hello@user"
}
###
